<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210720155659 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activitiesdisplay DROP FOREIGN KEY FK_EAFB9F6DCF60E67C');
        $this->addSql('ALTER TABLE ads DROP FOREIGN KEY FK_7EC9F620BC06EA63');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7BC06EA63');
        $this->addSql('ALTER TABLE commentreport DROP FOREIGN KEY FK_E02106DFA76ED395');
        $this->addSql('ALTER TABLE communauty DROP FOREIGN KEY FK_35C81BD6FAD8DA84');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FBF396750');
        $this->addSql('ALTER TABLE company_fav DROP FOREIGN KEY FK_72686407A76ED395');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757FAD8DA84');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F5F004ACF');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F6804FB49');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D95F004ACF');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D96804FB49');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7A76ED395');
        $this->addSql('ALTER TABLE event_fav DROP FOREIGN KEY FK_675425BCA76ED395');
        $this->addSql('ALTER TABLE fav_company DROP FOREIGN KEY FK_30AF0FDDA76ED395');
        $this->addSql('ALTER TABLE favoritecompany DROP FOREIGN KEY FK_8A398236FE6E88D7');
        $this->addSql('ALTER TABLE favoriteproduct DROP FOREIGN KEY FK_16CC8FD4FE6E88D7');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F55EEAC61');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F8D93D649');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CACF60E67C');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_182BA9BA115E1BBE');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176BF396750');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DBC06EA63');
        $this->addSql('ALTER TABLE postcomment DROP FOREIGN KEY FK_5D65518ABC06EA63');
        $this->addSql('ALTER TABLE postlike DROP FOREIGN KEY FK_B84FD43ABC06EA63');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4FBF094F');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADCF60E67C');
        $this->addSql('ALTER TABLE product_fav DROP FOREIGN KEY FK_96B4B470A76ED395');
        $this->addSql('ALTER TABLE productcomment DROP FOREIGN KEY FK_F3BF44BBC06EA63');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784BC06EA63');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784CF60E67C');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BC06EA63');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CF60E67C');
        $this->addSql('ALTER TABLE serviceoffercategories DROP FOREIGN KEY FK_BB59A884FBF094F');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0764FBF094F');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0768D93D649');
        $this->addSql('ALTER TABLE services DROP FOREIGN KEY FK_7332E1694FBF094F');
        $this->addSql('ALTER TABLE tarifadsuser DROP FOREIGN KEY FK_753A672D8D93D649');
        $this->addSql('ALTER TABLE userorder DROP FOREIGN KEY FK_507C2DE9BC06EA63');
        $this->addSql('CREATE TABLE userRV (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, role VARCHAR(50) NOT NULL, token VARCHAR(255) NOT NULL, emailValidated TINYINT(1) NOT NULL, actived TINYINT(1) NOT NULL, inscription_date DATE DEFAULT NULL, connected TINYINT(1) DEFAULT NULL, discr VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_557D7D6F85E0677 (username), UNIQUE INDEX UNIQ_557D7D6E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('DROP TABLE user');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_182BA9BA115E1BBE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_182BA9BA115E1BBE FOREIGN KEY (idparticipant) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE userorder DROP FOREIGN KEY FK_507C2DE9BC06EA63');
        $this->addSql('ALTER TABLE userorder ADD CONSTRAINT FK_507C2DE9BC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE activitiesdisplay DROP FOREIGN KEY FK_EAFB9F6DCF60E67C');
        $this->addSql('ALTER TABLE activitiesdisplay ADD CONSTRAINT FK_EAFB9F6DCF60E67C FOREIGN KEY (owner) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE ads DROP FOREIGN KEY FK_7EC9F620BC06EA63');
        $this->addSql('ALTER TABLE ads ADD CONSTRAINT FK_7EC9F620BC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7BC06EA63');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7BC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE commentreport DROP FOREIGN KEY FK_E02106DFA76ED395');
        $this->addSql('ALTER TABLE commentreport ADD CONSTRAINT FK_E02106DFA76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE communauty DROP FOREIGN KEY FK_35C81BD6FAD8DA84');
        $this->addSql('ALTER TABLE communauty ADD CONSTRAINT FK_35C81BD6FAD8DA84 FOREIGN KEY (createur) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FBF396750');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FBF396750 FOREIGN KEY (id) REFERENCES userRV (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_fav DROP FOREIGN KEY FK_72686407A76ED395');
        $this->addSql('ALTER TABLE company_fav ADD CONSTRAINT FK_72686407A76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757FAD8DA84');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757FAD8DA84 FOREIGN KEY (createur) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F5F004ACF');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F6804FB49');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90F5F004ACF FOREIGN KEY (sender) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90F6804FB49 FOREIGN KEY (recipient) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D95F004ACF');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D96804FB49');
        $this->addSql('ALTER TABLE discussionquote ADD CONSTRAINT FK_133A17D95F004ACF FOREIGN KEY (sender) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE discussionquote ADD CONSTRAINT FK_133A17D96804FB49 FOREIGN KEY (recipient) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7A76ED395');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7A76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE event_fav DROP FOREIGN KEY FK_675425BCA76ED395');
        $this->addSql('ALTER TABLE event_fav ADD CONSTRAINT FK_675425BCA76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE favoritecompany DROP FOREIGN KEY FK_8A398236FE6E88D7');
        $this->addSql('ALTER TABLE favoritecompany ADD CONSTRAINT FK_8A398236FE6E88D7 FOREIGN KEY (idUser) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE favoriteproduct DROP FOREIGN KEY FK_16CC8FD4FE6E88D7');
        $this->addSql('ALTER TABLE favoriteproduct ADD CONSTRAINT FK_16CC8FD4FE6E88D7 FOREIGN KEY (idUser) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F55EEAC61');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F8D93D649');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F55EEAC61 FOREIGN KEY (friend) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F8D93D649 FOREIGN KEY (user) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CACF60E67C');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACF60E67C FOREIGN KEY (owner) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176BF396750');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176BF396750 FOREIGN KEY (id) REFERENCES userRV (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DBC06EA63');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DBC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE postcomment DROP FOREIGN KEY FK_5D65518ABC06EA63');
        $this->addSql('ALTER TABLE postcomment ADD CONSTRAINT FK_5D65518ABC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE postlike DROP FOREIGN KEY FK_B84FD43ABC06EA63');
        $this->addSql('ALTER TABLE postlike ADD CONSTRAINT FK_B84FD43ABC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4FBF094F');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADCF60E67C');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4FBF094F FOREIGN KEY (company) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADCF60E67C FOREIGN KEY (owner) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE product_fav DROP FOREIGN KEY FK_96B4B470A76ED395');
        $this->addSql('ALTER TABLE product_fav ADD CONSTRAINT FK_96B4B470A76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE productcomment DROP FOREIGN KEY FK_F3BF44BBC06EA63');
        $this->addSql('ALTER TABLE productcomment ADD CONSTRAINT FK_F3BF44BBC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784BC06EA63');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784CF60E67C');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784BC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784CF60E67C FOREIGN KEY (owner) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BC06EA63');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CF60E67C');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BC06EA63 FOREIGN KEY (creator) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6CF60E67C FOREIGN KEY (owner) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE serviceoffercategories DROP FOREIGN KEY FK_BB59A884FBF094F');
        $this->addSql('ALTER TABLE serviceoffercategories ADD CONSTRAINT FK_BB59A884FBF094F FOREIGN KEY (company) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0764FBF094F');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0768D93D649');
        $this->addSql('ALTER TABLE serviceofferuser ADD CONSTRAINT FK_3B7BB0764FBF094F FOREIGN KEY (company) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE serviceofferuser ADD CONSTRAINT FK_3B7BB0768D93D649 FOREIGN KEY (user) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE services DROP FOREIGN KEY FK_7332E1694FBF094F');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E1694FBF094F FOREIGN KEY (company) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE tarifadsuser DROP FOREIGN KEY FK_753A672D8D93D649');
        $this->addSql('ALTER TABLE tarifadsuser ADD CONSTRAINT FK_753A672D8D93D649 FOREIGN KEY (user) REFERENCES userRV (id)');
        $this->addSql('ALTER TABLE fav_company DROP FOREIGN KEY FK_30AF0FDDA76ED395');
        $this->addSql('ALTER TABLE fav_company ADD CONSTRAINT FK_30AF0FDDA76ED395 FOREIGN KEY (user_id) REFERENCES userRV (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE Participation DROP FOREIGN KEY FK_182BA9BA115E1BBE');
        $this->addSql('ALTER TABLE Userorder DROP FOREIGN KEY FK_507C2DE9BC06EA63');
        $this->addSql('ALTER TABLE activitiesdisplay DROP FOREIGN KEY FK_EAFB9F6DCF60E67C');
        $this->addSql('ALTER TABLE ads DROP FOREIGN KEY FK_7EC9F620BC06EA63');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7BC06EA63');
        $this->addSql('ALTER TABLE commentReport DROP FOREIGN KEY FK_E02106DFA76ED395');
        $this->addSql('ALTER TABLE communauty DROP FOREIGN KEY FK_35C81BD6FAD8DA84');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FBF396750');
        $this->addSql('ALTER TABLE company_fav DROP FOREIGN KEY FK_72686407A76ED395');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757FAD8DA84');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F6804FB49');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F5F004ACF');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D95F004ACF');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D96804FB49');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7A76ED395');
        $this->addSql('ALTER TABLE event_fav DROP FOREIGN KEY FK_675425BCA76ED395');
        $this->addSql('ALTER TABLE favoritecompany DROP FOREIGN KEY FK_8A398236FE6E88D7');
        $this->addSql('ALTER TABLE favoriteproduct DROP FOREIGN KEY FK_16CC8FD4FE6E88D7');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F8D93D649');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F55EEAC61');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CACF60E67C');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176BF396750');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DBC06EA63');
        $this->addSql('ALTER TABLE postcomment DROP FOREIGN KEY FK_5D65518ABC06EA63');
        $this->addSql('ALTER TABLE postlike DROP FOREIGN KEY FK_B84FD43ABC06EA63');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADCF60E67C');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4FBF094F');
        $this->addSql('ALTER TABLE product_fav DROP FOREIGN KEY FK_96B4B470A76ED395');
        $this->addSql('ALTER TABLE productcomment DROP FOREIGN KEY FK_F3BF44BBC06EA63');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784CF60E67C');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784BC06EA63');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CF60E67C');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BC06EA63');
        $this->addSql('ALTER TABLE serviceoffercategories DROP FOREIGN KEY FK_BB59A884FBF094F');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0768D93D649');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0764FBF094F');
        $this->addSql('ALTER TABLE services DROP FOREIGN KEY FK_7332E1694FBF094F');
        $this->addSql('ALTER TABLE tarifadsuser DROP FOREIGN KEY FK_753A672D8D93D649');
        $this->addSql('ALTER TABLE fav_company DROP FOREIGN KEY FK_30AF0FDDA76ED395');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, password VARCHAR(4096) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, role VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, token VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, emailValidated TINYINT(1) NOT NULL, actived TINYINT(1) NOT NULL, inscription_date DATE DEFAULT NULL, connected TINYINT(1) DEFAULT NULL, dtype VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('DROP TABLE userRV');
        $this->addSql('ALTER TABLE activitiesdisplay DROP FOREIGN KEY FK_EAFB9F6DCF60E67C');
        $this->addSql('ALTER TABLE activitiesdisplay ADD CONSTRAINT FK_EAFB9F6DCF60E67C FOREIGN KEY (owner) REFERENCES user (id)');
        $this->addSql('ALTER TABLE ads DROP FOREIGN KEY FK_7EC9F620BC06EA63');
        $this->addSql('ALTER TABLE ads ADD CONSTRAINT FK_7EC9F620BC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7BC06EA63');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7BC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE commentReport DROP FOREIGN KEY FK_E02106DFA76ED395');
        $this->addSql('ALTER TABLE commentReport ADD CONSTRAINT FK_E02106DFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE communauty DROP FOREIGN KEY FK_35C81BD6FAD8DA84');
        $this->addSql('ALTER TABLE communauty ADD CONSTRAINT FK_35C81BD6FAD8DA84 FOREIGN KEY (createur) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FBF396750');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FBF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_fav DROP FOREIGN KEY FK_72686407A76ED395');
        $this->addSql('ALTER TABLE company_fav ADD CONSTRAINT FK_72686407A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE depense DROP FOREIGN KEY FK_34059757FAD8DA84');
        $this->addSql('ALTER TABLE depense ADD CONSTRAINT FK_34059757FAD8DA84 FOREIGN KEY (createur) REFERENCES user (id)');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F6804FB49');
        $this->addSql('ALTER TABLE discussion DROP FOREIGN KEY FK_C0B9F90F5F004ACF');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90F6804FB49 FOREIGN KEY (recipient) REFERENCES user (id)');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90F5F004ACF FOREIGN KEY (sender) REFERENCES user (id)');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D95F004ACF');
        $this->addSql('ALTER TABLE discussionquote DROP FOREIGN KEY FK_133A17D96804FB49');
        $this->addSql('ALTER TABLE discussionquote ADD CONSTRAINT FK_133A17D95F004ACF FOREIGN KEY (sender) REFERENCES user (id)');
        $this->addSql('ALTER TABLE discussionquote ADD CONSTRAINT FK_133A17D96804FB49 FOREIGN KEY (recipient) REFERENCES user (id)');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA7A76ED395');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE event_fav DROP FOREIGN KEY FK_675425BCA76ED395');
        $this->addSql('ALTER TABLE event_fav ADD CONSTRAINT FK_675425BCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE fav_company DROP FOREIGN KEY FK_30AF0FDDA76ED395');
        $this->addSql('ALTER TABLE fav_company ADD CONSTRAINT FK_30AF0FDDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favoritecompany DROP FOREIGN KEY FK_8A398236FE6E88D7');
        $this->addSql('ALTER TABLE favoritecompany ADD CONSTRAINT FK_8A398236FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE favoriteproduct DROP FOREIGN KEY FK_16CC8FD4FE6E88D7');
        $this->addSql('ALTER TABLE favoriteproduct ADD CONSTRAINT FK_16CC8FD4FE6E88D7 FOREIGN KEY (idUser) REFERENCES user (id)');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F8D93D649');
        $this->addSql('ALTER TABLE friendship DROP FOREIGN KEY FK_7234A45F55EEAC61');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F8D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE friendship ADD CONSTRAINT FK_7234A45F55EEAC61 FOREIGN KEY (friend) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CACF60E67C');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACF60E67C FOREIGN KEY (owner) REFERENCES user (id)');
        $this->addSql('ALTER TABLE Participation DROP FOREIGN KEY FK_182BA9BA115E1BBE');
        $this->addSql('ALTER TABLE Participation ADD CONSTRAINT FK_182BA9BA115E1BBE FOREIGN KEY (idparticipant) REFERENCES user (id)');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176BF396750');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176BF396750 FOREIGN KEY (id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DBC06EA63');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DBC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE postcomment DROP FOREIGN KEY FK_5D65518ABC06EA63');
        $this->addSql('ALTER TABLE postcomment ADD CONSTRAINT FK_5D65518ABC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE postlike DROP FOREIGN KEY FK_B84FD43ABC06EA63');
        $this->addSql('ALTER TABLE postlike ADD CONSTRAINT FK_B84FD43ABC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADCF60E67C');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4FBF094F');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADCF60E67C FOREIGN KEY (owner) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4FBF094F FOREIGN KEY (company) REFERENCES user (id)');
        $this->addSql('ALTER TABLE product_fav DROP FOREIGN KEY FK_96B4B470A76ED395');
        $this->addSql('ALTER TABLE product_fav ADD CONSTRAINT FK_96B4B470A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE productcomment DROP FOREIGN KEY FK_F3BF44BBC06EA63');
        $this->addSql('ALTER TABLE productcomment ADD CONSTRAINT FK_F3BF44BBC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784CF60E67C');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784BC06EA63');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784CF60E67C FOREIGN KEY (owner) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784BC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6CF60E67C');
        $this->addSql('ALTER TABLE review DROP FOREIGN KEY FK_794381C6BC06EA63');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6CF60E67C FOREIGN KEY (owner) REFERENCES user (id)');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6BC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
        $this->addSql('ALTER TABLE serviceoffercategories DROP FOREIGN KEY FK_BB59A884FBF094F');
        $this->addSql('ALTER TABLE serviceoffercategories ADD CONSTRAINT FK_BB59A884FBF094F FOREIGN KEY (company) REFERENCES user (id)');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0768D93D649');
        $this->addSql('ALTER TABLE serviceofferuser DROP FOREIGN KEY FK_3B7BB0764FBF094F');
        $this->addSql('ALTER TABLE serviceofferuser ADD CONSTRAINT FK_3B7BB0768D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE serviceofferuser ADD CONSTRAINT FK_3B7BB0764FBF094F FOREIGN KEY (company) REFERENCES user (id)');
        $this->addSql('ALTER TABLE services DROP FOREIGN KEY FK_7332E1694FBF094F');
        $this->addSql('ALTER TABLE services ADD CONSTRAINT FK_7332E1694FBF094F FOREIGN KEY (company) REFERENCES user (id)');
        $this->addSql('ALTER TABLE tarifadsuser DROP FOREIGN KEY FK_753A672D8D93D649');
        $this->addSql('ALTER TABLE tarifadsuser ADD CONSTRAINT FK_753A672D8D93D649 FOREIGN KEY (user) REFERENCES user (id)');
        $this->addSql('ALTER TABLE Userorder DROP FOREIGN KEY FK_507C2DE9BC06EA63');
        $this->addSql('ALTER TABLE Userorder ADD CONSTRAINT FK_507C2DE9BC06EA63 FOREIGN KEY (creator) REFERENCES user (id)');
    }
}
